### Create a new User:
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json


{
  "email": "john2@gmail.com",
  "username": "john",
  "password": "Password1!"
}



### sign user in:
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "username": "john",
  "password": "Password1!"
}


### Get all movies :jwt pass
GET http://localhost:8080/api/v1/movies
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2YWxlcmExIiwiaWF0IjoxNzA0MjQ0ODg2LCJleHAiOjE3MDY4MzY4ODZ9.oxv74hqojx5dzGW385JXIRjFQBfyHJQuqx9m1tJlYeIguETtbPXf3v5f5UETsNcjZFkPpI3AyOi15l9kduQN0g


### Get all movies : Basic pass
GET http://localhost:8080/api/v1/movies
Authorization: Basic john3 Password1!