### Create a new User:
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json


{
  "email": "john3@gmailjohn.com",
  "username": "john3",
  "password": "Password1!"
}



### sign user in:
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "username": "john3",
  "password": "Password1!"
}


### Get all movies :
GET http://localhost:8080/api/v1/movies
Authorization: BEARER eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huMyIsImlhdCI6MTcwMzg2Nzg2NSwiZXhwIjoxNzA2NDU5ODY1fQ.olSOAP8LngM6JSSz7EMlK7VklGq8vBiAWpfsaQEsagZUF4LWTPb2J8RU2M6RG4BXJxvRO89uaJVLx-zUJv_tdA



### Get all movies :
GET http://localhost:8080/api/v1/movies
Authorization: Basic john3 Password1!