### Add new Movie :
POST http://localhost:8080/api/v1/movies
Content-Type: application/json
Authorization: Basic john Password1!

{
  "title": "batman 8 team",
  "poster": "posterurl",
  "url": "url url!",
  "year": "1999",
  "genre": "action",
  "backdropScreen": "1999"
}


###  Add another  Movie :
POST http://localhost:8080/api/v1/movies
Content-Type: application/json
Authorization: Basic valera1 Password1!

{
  "title": "batman 7 team",
  "poster": "posterurl",
  "duration": "111",
  "url": "url url!",
  "year": "1999",
  "genre": "comedy",
  "backdropScreen": "1999"
}


### Get all Movies :
GET http://localhost:8080/api/v1/movies
Authorization: Basic valera1 Password1!


### Valid request get movie by id :
GET http://localhost:8080/api/v1/movies/1
Authorization: Basic valera1 Password1!


### Invalid request get movie by id :
GET http://localhost:8080/api/v1/movies/1111
Authorization: Basic john3 Password1!


### Update movie by id :
PUT http://localhost:8080/api/v1/movies/102
Content-Type: application/json
Authorization: Basic john Password1!

{
  "title": "batman 112 team",
  "poster": "posterurl",
  "duration": "111",
  "url": "url url!",
  "year": "1999",
  "genre": "comedy",
  "backdropScreen": "1999"
}


### Delete movie by id :
DELETE http://localhost:8080/api/v1/movies/52
Content-Type: application/json
Authorization: Basic john Password1!



### Get movie  page with sort and sort order:
GET http://localhost:8080/api/v1/movies/page?pageSize=1&pageNo=0&sortBy=id&sortDir=asc
Authorization: Basic john Password1!


### Get  Movies by Genre :
GET http://localhost:8080/api/v1/movies/genres
Authorization: Basic john Password1!


### Search  Movies by Genre name:
GET http://localhost:8080/api/v1/movies/search-by-genre?genre=Action
Authorization: Basic john Password1!


### Search  Movies by title:
GET http://localhost:8080/api/v1/movies/search?title=troll
Authorization: Basic john Password1!










