### Add new Movie :
POST http://localhost:8080/api/v1/movies
Content-Type: application/json
Authorization: Basic valera1 Password1!

{
  "title": "batman 6 team",
  "description": "man1 of rubber fist",
  "duration": 111,
  "genre": "cartoon32!",
  "cast": "Deni deVito1",
  "director": "Vilnev Fry1",
  "releaseDate": "1903-05-05"
}


###  Add another  Movie :
POST http://localhost:8080/api/v1/movies
Content-Type: application/json
Authorization: Basic valera1 Password1!

{
  "title": "batman 5 team",
  "description": "man of rubber fist",
  "duration": 200,
  "genre": "cartoon2!",
  "cast": "Deni deVito",
  "director": "Vilnev Fry",
  "releaseDate": "2005-05-05"
}


### Get all Movies :
GET http://localhost:8080/api/v1/movies
Authorization: Basic valera1 Password1!


### Valid request get movie by id :
GET http://localhost:8080/api/v1/movies/52
Authorization: Basic valera1 Password1!


### Invalid request get movie by id :
GET http://localhost:8080/api/v1/movies/1111
Authorization: Basic john3 Password1!


### Update movie by id :
PUT http://localhost:8080/api/v1/movies/1
Content-Type: application/json
Authorization: Basic admin admin

{
  "title": "batman 20 team",
  "description": "man of rubber fist and red shirt",
  "duration": 200,
  "genre": "cartoon!",
  "cast": "Ben deVito",
  "director": "Nolan Fry",
  "releaseDate": "2007-07-07"
}


### Delete movie by id :
DELETE http://localhost:8080/api/v1/movies/52
Content-Type: application/json
Authorization: Basic admin admin



### Get movie  page with sort and sort order:
GET http://localhost:8080/api/v1/movies/page?pageSize=2&pageNo=0&sortBy=id&sortDir=asc
Authorization: Basic john3 Password1!












