### Add new review :
POST http://localhost:8080/api/v1/movies/1/reviews
Content-Type: application/json
Authorization: Basic admin admin

{
  "textReview": "very Cool  movie2!",
  "rating": "8"
}


### Get all reviews by movie id  :
GET http://localhost:8080/api/v1/movies/1/reviews
Authorization: Basic john3 Password1!

### Get reviews by movie id, INVALID request movies id:
GET http://localhost:8080/api/v1/movies/-1/reviews
Authorization: Basic john3 Password1!


### Update review by id:Valid request
PUT http://localhost:8080/api/v1/movies/reviews/3
Content-Type: application/json
Authorization: Basic admin admin

{
  "textReview": "grom 4 stop",
  "rating": "1"
}


### Update review by id:Invalid request
PUT http://localhost:8080/api/v1/movies/reviews/-7
Content-Type: application/json
Authorization: Basic admin admin

{
  "textReview": "gavno vozvrashaetsya 6",
  "rating": "1"
}


### Delete review by id:Valid request
DELETE http://localhost:8080/api/v1/movies/reviews/3
Authorization: Basic admin admin



